dist: bionic
os: linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install -y cpanminus libperl-dev perl git net-tools
install:
  - "true"
perl:
  - "5.26"
script:
  - perl t/test.t
